name: "First Workflow"

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a welcome message
        run: echo "Welcome to our first workflow"

      - name: Checkout
        uses: actions/checkout@v5

      - name: List files
        run: ls -la
