name: First Work Flow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print a welcome message
        run: echo "Welcome to our first workflow"
